version: "3.7"

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - internal

  flask_app:
    build:
      context: ./app
    container_name: flask_app
    restart: always
    depends_on:
      - kafka
      - minio
    networks:
      - internal

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: "AKIAIOSFODNN7EXAMPLE"
      MINIO_ROOT_PASSWORD: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
      MINIO_SERVER_URL: "http://minio.autodoc.test:9000"
      MINIO_BROWSER_REDIRECT_URL: "http://minio.autodoc.test:9001/minio/ui"
    ports:
      - "9000:9000" 
      - "9001:9001"     
    volumes:
      - minio_data:/data   
    command: server /data --console-address ":9001"
    networks:
      - internal
    restart: unless-stopped
    depends_on:
      - nginx

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - internal

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - nginx
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka.autodoc.test:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - internal
    

networks:
  internal:
    driver: bridge

volumes:
  minio_data:
